### ISSUE TITLE
Maven 3.5.2 - libjansi.so not a dynamic executable

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/brew#516]
```
linuxbrew@marvin:~ $ brew upgrade maven -v
==> Upgrading 1 outdated package, with result:
maven 3.5.2
==> Upgrading maven
rm /home/linuxbrew/.linuxbrew/bin/mvn
rm /home/linuxbrew/.linuxbrew/bin/mvn.cmd
rm /home/linuxbrew/.linuxbrew/bin/mvnDebug
rm /home/linuxbrew/.linuxbrew/bin/mvnDebug.cmd
rm /home/linuxbrew/.linuxbrew/bin/mvnyjp
==> Downloading https://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/maven-3.5.2.tar.gz
==> Verifying maven-3.5.2.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/maven-3.5.2.tar.gz
ln -s ../Cellar/maven/3.5.0/bin/mvn mvn
ln -s ../Cellar/maven/3.5.0/bin/mvn.cmd mvn.cmd
ln -s ../Cellar/maven/3.5.0/bin/mvnDebug mvnDebug
ln -s ../Cellar/maven/3.5.0/bin/mvnDebug.cmd mvnDebug.cmd
ln -s ../Cellar/maven/3.5.0/bin/mvnyjp mvnyjp
Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd /home/linuxbrew/.linuxbrew/Cellar/maven/3.5.2/libexec/lib/jansi-native/freebsd64/libjansi.so
        not a dynamic executable

```

**Comment by sjackman** [comment]
Thanks for the bug report, Torsten.
This bug will be resolved by PR https://github.com/Linuxbrew/brew/pull/517

**Comment by sjackman** [comment]
I've merged PR #517. Could you please try…
```sh
brew update
brew --version
brew upgrade maven
```

**Comment by tseemann** [comment]
It installs now.

**Comment by thedrow** [comment]
I still have the problem described by this issue. I have the latest linuxbrew installed (1.3.6).
Is this fix released?

**Comment by thedrow** [comment]
Looks like it isn't and brew stashes changes of it's own repo so I can't apply the patch manually.

**Comment by sjackman** [comment]
No, it's not released yet. If you apply the patch manually and commit it, it should survive through a `brew update`.

**Comment by iMichka** [comment]
It's here: https://github.com/Linuxbrew/brew/commit/44564b47d63b492af4b5bd0452f6716cfac778e9

It will be available when we tag 1.3.7

**Comment by sjackman** [comment]
Try…
```sh
git -C $(brew --repo) cherry-pick 44564b4
```

**Comment by heuermh** [comment]
Sorry to comment on a closed issue, I'm hitting this in Docker builds that extend `FROM linuxbrew/linuxbrew`, e.g. https://hub.docker.com/r/heuermh/dsh-bio-dev/builds/bqs4mma27hkut5dybofabea/.  Is there something I need to do to pick up the fix?

**Comment by sjackman** [comment]
The above build log is from over a month ago, before PR https://github.com/Linuxbrew/brew/pull/517 was merged, which resolved this issue. Your most recent build of today is successful. https://hub.docker.com/r/heuermh/dsh-bio-dev/builds/

**Comment by heuermh** [comment]
> Your most recent build of today is successful.

Well, look at that.  Nice when things work themselves out.  :)

Sorry for the noise.

**Comment by sjackman** [comment]
No worries. Glad it worked for you. =)
