### ISSUE TITLE
brew info on python packages gives weird error message 

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/brew#557]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

Not sure if this is harmful, but I ran
```
brew info python
```
and get 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
```
Similar messages show up on numpy and scipy as well. 

Here's the output from brew doctor:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/linuxbrew/.linuxbrew/bin/icu-config
  /home/linuxbrew/.linuxbrew/bin/xslt-config
  /home/linuxbrew/.linuxbrew/bin/python3.6m-config
  /home/linuxbrew/.linuxbrew/bin/python2.7-config
  /home/linuxbrew/.linuxbrew/bin/Magick++-config
  /home/linuxbrew/.linuxbrew/bin/nspr-config
  /home/linuxbrew/.linuxbrew/bin/sdl2-config
  /home/linuxbrew/.linuxbrew/bin/freetype-config
  /home/linuxbrew/.linuxbrew/bin/MagickCore-config
  /home/linuxbrew/.linuxbrew/bin/libgcrypt-config
  /home/linuxbrew/.linuxbrew/bin/croco-0.6-config
  /home/linuxbrew/.linuxbrew/bin/gpg-error-config
  /home/linuxbrew/.linuxbrew/bin/gdlib-config
  /home/linuxbrew/.linuxbrew/bin/xml2-config
  /home/linuxbrew/.linuxbrew/bin/ncurses6-config
  /home/linuxbrew/.linuxbrew/bin/pkg-config
  /home/linuxbrew/.linuxbrew/bin/llvm-config
  /home/linuxbrew/.linuxbrew/bin/gsl-config
  /home/linuxbrew/.linuxbrew/bin/ncursesw6-config
  /home/linuxbrew/.linuxbrew/bin/libwmf-config
  /home/linuxbrew/.linuxbrew/bin/pcre-config
  /home/linuxbrew/.linuxbrew/bin/python3-config
  /home/linuxbrew/.linuxbrew/bin/jemalloc-config
  /home/linuxbrew/.linuxbrew/bin/caca-config
  /home/linuxbrew/.linuxbrew/bin/guile-config
  /home/linuxbrew/.linuxbrew/bin/MagickWand-config
  /home/linuxbrew/.linuxbrew/bin/python2-config
  /home/linuxbrew/.linuxbrew/bin/libpng-config
  /home/linuxbrew/.linuxbrew/bin/libpng16-config
  /home/linuxbrew/.linuxbrew/bin/wx-config
  /home/linuxbrew/.linuxbrew/bin/curl-config
  /home/linuxbrew/.linuxbrew/bin/cups-config
  /home/linuxbrew/.linuxbrew/bin/orbit2-config
  /home/linuxbrew/.linuxbrew/bin/krb5-config
  /home/linuxbrew/.linuxbrew/bin/autoopts-config
  /home/linuxbrew/.linuxbrew/bin/python3.6-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lua@5.1
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
```

**Comment by sjackman** [comment]
Thanks for the bug report. I'll look into it.

**Comment by Char-Aznable** [comment]
Actually,  this does cause issues for brew upgrade:

```
brew upgrade adwaita-icon-theme
==> Upgrading 1 outdated package, with result:
adwaita-icon-theme 3.26.1
xcb-proto: PythonRequirement unsatisfied!
libxcb: PythonRequirement unsatisfied!
mesa: PythonRequirement unsatisfied!
Error: Unsatisfied requirements failed this build.
```

**Comment by sjackman** [comment]
Please report `brew --version`. Does `brew install python` resolve this issue?

**Comment by Char-Aznable** [comment]
```
brew --version
Homebrew 1.4.1-53-gdd3b579
```
and 
```
brew install python
Warning: python 2.7.14_3 is already installed
```
Here's brew info python
```
python: stable 2.7.14, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/scratch/.linuxbrew/Cellar/python/2.7.14 (5,492 files, 101.0MB)
  Built from source on 2017-10-24 at 19:21:40 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_2 (5,491 files, 101.2MB)
  Built from source on 2018-01-05 at 22:18:59 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_3 (5,491 files, 101.2MB) *
  Built from source on 2018-01-07 at 23:55:55 with: --with-tcl-tk
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: xz ✔, pkg-config ✔, unzip ✔
Required: openssl ✔, bzip2 ✔, ncurses ✔, zlib ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: tcl-tk ✔, berkeley-db@4 ✔
==> Options
--with-berkeley-db@4
	Build with berkeley-db@4 support
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--with-unicode-ucs4
	Build unicode support with UCS4
--without-gdbm
	Build without gdbm support
--without-poll
	Disable select.poll
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
This formula installs a python2 executable to /scratch/.linuxbrew/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/scratch/.linuxbrew/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /scratch/.linuxbrew/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p 
  echo 'import site; site.addsitedir("/scratch/.linuxbrew/lib/python2.7/site-packages")' >> homebrew.pth
```

**Comment by maxim-belkin** [comment]
@Char-Aznable what's the output of `which -a brew`?

**Comment by maxim-belkin** [comment]
And the second question: what is your `PATH`?
```
echo -e ${PATH//:/\\n} # Bash
```

**Comment by sjackman** [comment]
@Char-Aznable I wasn't able to reproduce your exact error message. In a fresh Docker container I was able to get this similar error message:
```
❯❯❯ brew info python
…
--HEAD
	Install HEAD version
sh: 1: python: not found
sh: 1: python: not found
==> Caveats
…
```
I suspect that resolving this issue will also resolve your issue.

**Comment by sjackman** [comment]
I'm hoping that this PR resolves your issue: https://github.com/Linuxbrew/brew/pull/559

**Comment by Char-Aznable** [comment]
I accidentally did a brew update today and the issue is gone. Both the error messages and the last paragraph of the caveat are gone. Now brew info python looks like:
```
python: stable 2.7.14, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/scratch/.linuxbrew/Cellar/python/2.7.14 (5,492 files, 101.0MB)
  Built from source on 2017-10-24 at 12:21:40 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_2 (5,491 files, 101.2MB)
  Built from source on 2018-01-05 at 14:18:59 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_3 (5,491 files, 101.2MB) *
  Built from source on 2018-01-07 at 15:55:55 with: --with-tcl-tk
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: xz ✔, pkg-config ✔, unzip ✔
Required: openssl ✔, bzip2 ✔, ncurses ✔, zlib ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: tcl-tk ✔, berkeley-db@4 ✔
==> Options
--with-berkeley-db@4
	Build with berkeley-db@4 support
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--with-unicode-ucs4
	Build unicode support with UCS4
--without-gdbm
	Build without gdbm support
--without-poll
	Disable select.poll
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
==> Caveats
This formula installs a python2 executable to /scratch/.linuxbrew/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/scratch/.linuxbrew/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /scratch/.linuxbrew/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
```
Here's the current brew --version (sorry I forgot to include the homebrew-core version earlier):
```
Homebrew 1.4.1-53-gdd3b579
Homebrew/homebrew-core (git revision d1f32; last commit 2018-01-08)
```
**However, I have homebrew-core of an earlier version on another machine that still has exactly the same issue, where brew --version is**:
```
Homebrew 1.4.1-53-gdd3b579
Homebrew/homebrew-core (git revision fe4a99; last commit 2018-01-05
)
```
 @maxim-belkin  Here's the output for which -a brew (/home/linuxbrew/.linuxbrew is a symlink from /scratch/.linuxbrew) and my $PATH
```
which -a brew
/home/linuxbrew/.linuxbrew/bin/brew
/scratch/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/bin/brew
/scratch/.linuxbrew/bin/brew
```
```
echo -e ${PATH//:/\\n}
/home/linuxbrew/.linuxbrew/opt/python/libexec/bin
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/bin
/scratch/.linuxbrew/sbin
/scratch/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/opt/python/libexec/bin
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/bin
/scratch/.linuxbrew/sbin
/scratch/.linuxbrew/bin
/usr/lib64/qt-3.3/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/usr/sbin
/sbin
/home/linuxbrew/.linuxbrew/opt/go/libexec/bin
/home/linuxbrew/.linuxbrew/opt/go/libexec/bin
```

**Comment by Char-Aznable** [comment]
@sjackman  I have not tried PR #559 but I can confirm that on the caveats.rb are the same on the two machines

**Comment by sjackman** [comment]
I've merged the related PR https://github.com/Linuxbrew/brew/pull/560

**Comment by sjackman** [comment]
Do you still see an error message from `brew info python` after `brew update`? Please report `brew --version` if you do.

**Comment by Char-Aznable** [comment]
I still see the error message after brew update. 
```
brew --version
Homebrew 1.4.1-54-g0e8851b
Homebrew/homebrew-core (git revision 4ac008; last commit 2018-01-08)
```
Note that linuxbrew is installed in ~/.linuxbrew on this machine. I wonder if this causes some path issue.

**Comment by sjackman** [comment]
Please report…
```sh
brew config
which -a python
/usr/bin/python -c "import site; print(site.getusersitepackages())"
python -c "import site; print(site.getusersitepackages())"
```

**Comment by Char-Aznable** [comment]
```
brew config
HOMEBREW_VERSION: 1.4.1-54-g0e8851b
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 0e8851be348f3765defcaf0a78ea1431d65cc785
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 4ac00848ad54ad38e9359b11800f983f763ad343
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /home/cazn/.linuxbrew
HOMEBREW_REPOSITORY: /home/cazn/.linuxbrew
HOMEBREW_CELLAR: /home/cazn/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/cazn/.cache
HOMEBREW_CELLAR: /home/cazn/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /home/cazn/.cache
HOMEBREW_PREFIX: /home/cazn/.linuxbrew
HOMEBREW_REPOSITORY: /home/cazn/.linuxbrew
HOMEBREW_TEMP: /tmp
CPU: 16-core 64-bit westmere
Homebrew Ruby: 2.3.3 => /home/cazn/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build 
Git: 2.15.1 => /home/cazn/.linuxbrew/bin/git
Curl: 7.57.0 => /home/cazn/.linuxbrew/opt/curl/bin/curl
Perl: /home/cazn/.linuxbrew/bin/perl => /home/cazn/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/cazn/.linuxbrew/opt/python/libexec/bin/python => /home/cazn/.linuxbrew/Cellar/python/2.7.14_2/bin/python2.7
Ruby: /home/cazn/.linuxbrew/bin/ruby => /home/cazn/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby
Java: openjdk version "1.8.0_91"
Kernel: Linux 2.6.32-642.1.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.8 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0
xorg: 20170115

```

```
which -a python

/home/cazn/.linuxbrew/opt/python/libexec/bin/python
/home/cazn/.linuxbrew/bin/python
/usr/bin/python

```

```
/usr/bin/python -c "import site; print(site.getusersitepackages())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'

```

```
python -c "import site; print(site.getusersitepackages())"
/home/cazn/.local/lib/python2.7/site-packages
```

**Comment by sjackman** [comment]
This issue seems relevant: https://github.com/pypa/virtualenv/issues/804#issuecomment-337372751
Is Virtualenv activated when you're running `brew`?

**Comment by sjackman** [comment]
Modifying the `site.py` that `/usr/bin/python` is using should resolve this issue for you.
See https://github.com/pypa/virtualenv/issues/804#issuecomment-323088525

**Comment by Char-Aznable** [comment]
No, I've never had any virtualenv setup on that machine. Unfortunately, the site.py is in  /usr/lib/python2.6/site-packages/site.py and our system admin would not allow modification of files under /usr. Is there any other workaround for this?

**Comment by sjackman** [comment]
It seems that Python 2.6 `site.py` does not provide `site.getusersitepackages()`. Can anyone confirm?

**Comment by sjackman** [comment]
As a hack workaround, try changing…
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/language/python.rb#L45
```diff
-      if !OS.mac? && which(python).nil?
+      if true || !OS.mac? && which(python).nil?
```

**Comment by sjackman** [comment]
I've just merged Homebrew/brew 1.4.3 into Linuxbrew/brew master. It has this change, which seems relevant to this issue.

> upgrade: skip formula if upgrade fails due to unsatisfied requirement.

https://github.com/Homebrew/brew/releases/tag/1.4.3

Try
```sh
brew update
brew --version
brew upgrade
```

**Comment by Char-Aznable** [comment]
I can confirm that neither /usr/lib64/python2.6/site.py or /usr/lib/python2.6/site-packages/site.py has site.getusersitepackages().

Running brew update and brew --version:
```
Homebrew 1.4.2-19-g77a15dc-dirty
Homebrew/homebrew-core (git revision 1be50; last commit 2018-01-09)
```
and it still has this issue. But the workaround 
```
-      if !OS.mac? && which(python).nil?
+      if true || !OS.mac? && which(python).nil?
```
in ~/.linuxbrew/Library/Homebrew/language/python.rb works for me.

**Comment by maxim-belkin** [comment]
Interesting... So, if you execute:
```
virtualenv
```
or
```
ls ~/.pyenv
```
you get error messages?

**Comment by maxim-belkin** [comment]
and what do you get with 
```
compgen -A variable PYTHON
```
?

**Comment by sjackman** [comment]
My conclusion is that `brew info python` fails when `/usr/bin/python` is Python 2.6. We should be able to fix that by checking that executing `python` is successful. Currently the exit status of `python` is being ignored.
```ruby
Pathname.new(`#{python} -c "import site; print(site.getusersitepackages())"`.chomp)
```
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/language/python.rb#L48

**Comment by sjackman** [comment]
@Char-Aznable I'm hoping that this PR https://github.com/Linuxbrew/brew/pull/563 will resolve your issue.

**Comment by Char-Aznable** [comment]
@maxim-belkin virtualenv and ~/.pyenv don't exist on my system. 
```
compgen -A variable PYTHON
PYTHONPATH
```

**Comment by Char-Aznable** [comment]
On the other machine that had the issue disappear in Homebrew 1.4.1-53-gdd3b579 now has the issue recur with brew --version:
```
Homebrew 1.4.2-19-g77a15dc
Homebrew/homebrew-core (no git repository)
```
```
brew info python
python: stable 2.7.14, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/scratch/.linuxbrew/Cellar/python/2.7.14 (5,492 files, 101.0MB)
  Built from source on 2017-10-24 at 19:21:40 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_2 (5,491 files, 101.2MB)
  Built from source on 2018-01-05 at 22:18:59 with: --with-tcl-tk
/scratch/.linuxbrew/Cellar/python/2.7.14_3 (5,491 files, 101.2MB) *
  Built from source on 2018-01-07 at 23:55:55 with: --with-tcl-tk
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: xz ✔, pkg-config ✔, unzip ✔
Required: openssl ✔, bzip2 ✔, ncurses ✔, zlib ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: tcl-tk ✔, berkeley-db@4 ✔
==> Options
--with-berkeley-db@4
	Build with berkeley-db@4 support
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--with-unicode-ucs4
	Build unicode support with UCS4
--without-gdbm
	Build without gdbm support
--without-poll
	Disable select.poll
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
This formula installs a python2 executable to /scratch/.linuxbrew/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/scratch/.linuxbrew/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /scratch/.linuxbrew/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p
  echo 'import site; site.addsitedir("/scratch/.linuxbrew/lib/python2.7/site-packages")' >> homebrew.pth
```

**Comment by sjackman** [comment]
@Char-Aznable I've merged PR https://github.com/Linuxbrew/brew/pull/563. Does it resolve your issue?
```sh
brew update
brew --version
brew info python
```

**Comment by Char-Aznable** [comment]
@sjackman Weird, I got even more errors. First, it seems homebrew-core repository is not detected:
```
brew update && brew --version
Already up-to-date.
Homebrew 1.4.2-20-gc85a991
**Homebrew/homebrew-core (no git repository)**
```
Now brew info python becomes:
```
...

Message from syslogd@thr at Jan 10 03:16:55 ...
 aceback (most recent call last):

Message from syslogd@thr at Jan 10 03:16:55 ...
 File "<string>", line 1, in <module>

Message from syslogd@thr at Jan 10 03:16:55 ...
 tributeError

Message from syslogd@thr at Jan 10 03:16:55 ...
 

Message from syslogd@thr at Jan 10 03:16:55 ...
 odule' object has no attribute 'getusersitepackages'

Message from syslogd@thr at Jan 10 03:16:55 ...
 

Message from syslogd@thr at Jan 10 03:16:55 ...
 aceback (most recent call last):

Message from syslogd@thr at Jan 10 03:16:55 ...
 File "<string>", line 1, in <module>

Message from syslogd@thr at Jan 10 03:16:55 ...
 tributeError

Message from syslogd@thr at Jan 10 03:16:55 ...
 

Message from syslogd@thr at Jan 10 03:16:55 ...
 odule' object has no attribute 'getusersitepackages'

Message from syslogd@thr at Jan 10 03:16:55 ...
 
==> Caveats
This formula installs a python2 executable to /scratch/.linuxbrew/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/scratch/.linuxbrew/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /scratch/.linuxbrew/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /home/cazn/.local/lib/python2.7/site-packages
  echo 'import site; site.addsitedir("/scratch/.linuxbrew/lib/python2.7/site-packages")' >> /home/cazn/.local/lib/python2.7/site-packages/homebrew.pth
```

**Comment by Char-Aznable** [comment]
Is there any update on this issue? I still see the errors as of version
```
Homebrew 1.4.2-20-gc85a991
Homebrew/homebrew-core (git revision 418a3; last commit 2018-01-11)
```

**Comment by sjackman** [comment]
Hi, @Char-Aznable. I'm not able to reproduce your issue using Docker and CentOS release 6.9 (Final) with Python 2.6.6 with Linuxbrew 1.4.3 using this Dockerfile: https://github.com/Linuxbrew/docker/blob/master/centos6/Dockerfile

It'll be difficult for me to troubleshoot this issue unless I can reproduce it. If you can give instructions to reproduce the issue inside a Docker image, I'll have a better chance of being able to help you.

**Comment by Char-Aznable** [comment]
@sjackman I think I found the error. It seems that Utils.popen_read() is leaking the stderr from the system call. I made the following the change:
```
diff --git a/Library/Homebrew/language/python.rb b/Library/Homebrew/language/python.rb
index 3a31a5a99..09742d3a2 100644
--- a/Library/Homebrew/language/python.rb
+++ b/Library/Homebrew/language/python.rb
@@ -42,8 +42,8 @@ module Language
     end

     def self.user_site_packages(python)
-      output = Utils.popen_read(python, "-c", "import site; print(site.getusersitepackages())").chomp
-      if !$CHILD_STATUS.success? || output.empty?
+      output, error, s = Open3.capture3(python, "-c", "import site; print(site.getusersitepackages())")
+      if s.success? || output.empty?
         return Pathname.new("#{ENV["HOME"]}/.local/lib/python2.7/site-packages")
       end
       Pathname.new(output)
```
then the issue is fixed.

**Comment by sjackman** [comment]
Weird. `Utils.popen_read()` closes stderr.
See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/utils/popen.rb#L16
I don't know about `Open3.capture3`. That's a useful function.
Are you able to figure out why `Utils.popen_read` isn't working as expected?

**Comment by Char-Aznable** [comment]
Honest, I'm a ruby newbie, let alone the homebrew internal. But here's a minimal example that I can consistently reproduce the error:
```
#!/usr/bin/env ruby

def popen(args, mode, options = {})
  IO.popen("-", mode) do |pipe|
    if pipe
      return pipe.read unless block_given?
      yield pipe
    else
      options[:err] ||= :close unless ENV["HOMEBREW_STDERR"]
      begin
        exec(*args, options)
      rescue Errno::ENOENT
        $stderr.puts "brew: command not found: #{args[0]}" unless options[:err] == :close
        exit! 127
      rescue SystemCallError
        $stderr.puts "brew: exec failed: #{args[0]}" unless options[:err] == :close
        exit! 1
      end
    end
  end
end

popen("/usr/bin/python -c 'import site; print(site.getusersitepackages())'", "rb")
```
which gives as in brew info python:
```
Message from syslogd@thr at Jan 12 14:43:10 ...
 aceback (most recent call last):

Message from syslogd@thr at Jan 12 14:43:10 ...
 File "<string>", line 1, in <module>

Message from syslogd@thr at Jan 12 14:43:10 ...
 tributeError

Message from syslogd@thr at Jan 12 14:43:10 ...


Message from syslogd@thr at Jan 12 14:43:10 ...
 odule' object has no attribute 'getusersitepackages'

Message from syslogd@thr at Jan 12 14:43:10 ...
```
Somehow popen() is interacting syslogd? I won't be able to go futher beyond this given my limited knowledge of ruby. I guess the question is do we need to go over Utils.popen_read() here anyway? It seems to me that chain of function calls is just trying to trap the stdout and stderr, which we don't really need here.

**Comment by sjackman** [comment]
I'm not sure why syslogd is getting involved on your system. That's odd. In CentOS 6.9 on Docker, I put your above Ruby code in a file `foo.rb` and tested it. I get…
```
❯❯❯ ruby foo.rb
(no output here)
❯❯❯ HOMEBREW_STDERR=1 ruby foo.rb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
```
Could you please report the output of
```
HOMEBREW_STDERR=1 ruby foo.rb
HOMEBREW_STDERR=1 brew config
```

**Comment by Char-Aznable** [comment]
```
HOMEBREW_STDERR=1 ruby foo.rb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
```

```
HOMEBREW_STDERR=1 brew config

HOMEBREW_VERSION: 1.4.3
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: c85a991d105d19b55216f85e5f82b1eae2766e3b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: a24db9f3a3de67bd31134b612c995e2015b1d676
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/cazn/.linuxbrew
HOMEBREW_REPOSITORY: /home/cazn/.linuxbrew
HOMEBREW_CELLAR: /home/cazn/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/cazn/.cache
HOMEBREW_CELLAR: /home/cazn/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /home/cazn/.cache
HOMEBREW_PREFIX: /home/cazn/.linuxbrew
HOMEBREW_REPOSITORY: /home/cazn/.linuxbrew
HOMEBREW_STDERR: 1
HOMEBREW_TEMP: /tmp
CPU: 16-core 64-bit westmere
Homebrew Ruby: 2.3.3 => /home/cazn/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build
Git: 2.15.1 => /home/cazn/.linuxbrew/bin/git
Curl: 7.57.0 => /home/cazn/.linuxbrew/opt/curl/bin/curl
Perl: /home/cazn/.linuxbrew/bin/perl => /home/cazn/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/cazn/.linuxbrew/opt/python/libexec/bin/python => /home/cazn/.linuxbrew/Cellar/python/2.7.14_3/bin/python2.7
Ruby: /home/cazn/.linuxbrew/bin/ruby => /home/cazn/.linuxbrew/Cellar/ruby/2.5.0/bin/ruby
Java: openjdk version "1.8.0_91"
Kernel: Linux 2.6.32-642.1.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.8 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0
xorg: 20170115
```

**Comment by sjackman** [comment]
That's odd that you don't see the error message from Python in `brew config`. It seems like a workaround for you may be
```
export HOMEBREW_STDERR=1
```
Does that work for you?

**Comment by Char-Aznable** [comment]
No, HOMEBREW_STDERR=1 brew info python still gives the error. I'm a bit confused here. Why would "brew info python" look up python in /usr/bin anyway given that there's a brew installed python? Also, why you bre w config give the error message from python -- I thought the error message is python checking for getusersitepackages()?

**Comment by sjackman** [comment]
Sorry, my mistake. I meant…
```
HOMEBREW_STDERR=1 brew info python
```

**Comment by Char-Aznable** [comment]
Like I said, 
```
HOMEBREW_STDERR=1 brew info python
```
 still gives the error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
```

**Comment by sjackman** [comment]
The error message is expected. You don't see the `syslogd` craziness with `HOMEBREW_STDERR=1`, correct?

**Comment by Char-Aznable** [comment]
That's correct.

**Comment by sjackman** [comment]
I can't say why `Utils.popen_read` is interacting so strangely with your system, and I'm afraid that I don't have time time at the moment to troubleshoot it. If the error message is not causing you any direct grief for now, I'd suggest simply ignoring it. Does `HOMEBREW_STDERR=1 brew upgrade` work for you?

**Comment by Char-Aznable** [comment]
HOMEBREW_STDERR=1 brew upgrade gives this git error the first time I run it but it's fine on the second run.
```
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html

error: unknown option `local'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    -f, --file <FILE>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true
```
I think Somehow the ancient version of git in /usr/bin/git is picked up. In any case, I think it's OK for now if you think these erros are not doing actual harm.

**Comment by sjackman** [comment]
Yeah, that's what's happening. It's supposed to prefer the brewed git, but that may have changed recently with the addition of `ENV_FITLERING`. I will look into the `git` issue, but next month.

**Comment by Char-Aznable** [comment]
Alright, thanks for working on this.

**Comment by sjackman** [comment]
Thanks for helping with the troubleshooting.
