### ISSUE TITLE
Brew gets stuck in a loop

### ISSUE THREAD

**Issue by half2me** [Linuxbrew/brew#600]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I maintain a brew repo for gsreamer and some plugins for it, including video acceleration frameworks. [Link](https://github.com/half2me/homebrew-gstreamer) I use this regularly  to install gstreamer and plugins to PCs using it.
- What happened (include command output)
Around 2-3 weeks ago brew updated, and since then, whenever I try to install any of my formulas, it just hangs. I did not change the formula, I used the same procedure as before, but it will literally hang for hours on end. Now, the interesting thing is, I ran strace on it, to see what it was doing, and what it was waiting for. It seems to get stuck in some loop when listing dependencies, as it keeps doing the same cylce again and again. It does a `stat()` and `lstat()` on a few ruby formulas, then it just starts over with the exact same formulas. It does this repeatedly, and won't go any farther into the installation. I have bottles available for my formula, so its getting stuck on the dependency detection step.

- Step-by-step reproduction instructions (by running `brew` commands)
Reproducing this problem is pretty simple, just tap my repo with `brew tap half2me/gstreamer`
after, install a formula, for example: `brew install half2me/gstreamer/gst-plugins-base`
It will just spin on and on at the dependency step, and not go any further :/

**Comment by iMichka** [comment]
Hi. Please provide the output of
brew doctor
brew config 

Does this happen with other formulae too? It may be that there is something broken in your tap.

**Comment by sjackman** [comment]
My best guess is that there's a circular dependency cycle. To try to track it down, run `brew deps` on each formula in your tap. See which get stuck and go from there.

**Comment by andbleo** [comment]
I started seeing this issue a day or two ago.  I ran the uninstall script located at the bottom here (https://github.com/Linuxbrew/legacy-linuxbrew/issues/49), so I could start from scratch.  After installing Linuxbrew again, I can install some packages but not others.  ripgrep is an example of a package I can't install and tmux is an example of one I can install.  Here is the output of brew doctor and brew config:
```
Your system is ready to brew.
```
```
HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 0da98e625677eeff4b772be3508d9528e56ca686
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 5276527244d7a00fcaa81d2d751e7d6077521aa4
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/andrew/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: 12-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: N/A
Java: N/A
Kernel: Linux 4.13.0-36-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.4 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

Here is a small sample of some of the strace dump I am seeing when I try to install ripgrep:
```
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb", {st_mode=S_IFREG|0644, st_size=1904, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb", {st_mode=S_IFREG|0644, st_size=1904, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/util-macros.rb", {st_mode=S_IFREG|0644, st_size=730, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/util-macros.rb", {st_mode=S_IFREG|0644, st_size=730, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xineramaproto.rb", {st_mode=S_IFREG|0644, st_size=819, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xineramaproto.rb", {st_mode=S_IFREG|0644, st_size=819, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xineramaproto.rb", {st_mode=S_IFREG|0644, st_size=819, ...}) = 0
open("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xineramaproto.rb", O_RDONLY) = 7
fcntl(7, F_GETFD)                       = 0
fcntl(7, F_SETFD, FD_CLOEXEC)           = 0
ioctl(7, TCGETS, 0x7ffde8c34000)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(7, {st_mode=S_IFREG|0644, st_size=819, ...}) = 0
lseek(7, 0, SEEK_CUR)                   = 0
read(7, "class Xineramaproto < Formula\n  "..., 819) = 819
read(7, "", 8192)                       = 0
close(7)                                = 0
stat("https://www.x.org/archive/individual/proto/xineramaproto-1.2.1.tar.bz2", 0x7ffde8c33b60) = -1 ENOENT (No such file or directory)
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb", {st_mode=S_IFREG|0644, st_size=1904, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb", {st_mode=S_IFREG|0644, st_size=1904, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/util-macros.rb", {st_mode=S_IFREG|0644, st_size=730, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/util-macros.rb", {st_mode=S_IFREG|0644, st_size=730, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xproto.rb", {st_mode=S_IFREG|0644, st_size=1436, ...}) = 0
lstat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xproto.rb", {st_mode=S_IFREG|0644, st_size=1436, ...}) = 0
stat("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xproto.rb", {st_mode=S_IFREG|0644, st_size=1436, ...}) = 0
open("/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xproto.rb", O_RDONLY) = 7
```

It continues to try stat and lstat various xorg files, cant find them, and continues on and on and on.

**Comment by iMichka** [comment]
See #6363. Can you update and try again?

**Comment by andbleo** [comment]
The output data I just provided was from reinstalling Linuxbrew about 30 minutes ago.  When I ran `brew update`, it says it is already up-to-date.  What is #6363?

**Comment by iMichka** [comment]
Woups, https://github.com/Linuxbrew/homebrew-core/pull/6363, which I merged 11 minutes ago :)

**Comment by andbleo** [comment]
I verified that my Linuxbrew now has commit 20b70bedebe613fc947f99a6619909eb4e7a242b for homebrew-core, but I am still seeing the same behavior as the strace output I pasted before.

**Comment by andbleo** [comment]
Hmm, hold on.  I let it run for several minutes and now it seems to be working.

**Comment by iMichka** [comment]
Yes, it takes a little bit of time because it needs to resolve the dependency tree. Glad it is fixed for you. There may still be problems here and there, due to the whole python@2/python migration, so testing and pull requests are welcome.

**Comment by andbleo** [comment]
Yeah, ripgrep transitively depends on python3 which now depends on xorg, which is why it takes so long.  Thanks for the help!
